export const browserCoreExamples = [
  "kova browser status",
  "kova browser start",
  "kova browser start --headless",
  "kova browser stop",
  "kova browser tabs",
  "kova browser open https://example.com",
  "kova browser focus abcd1234",
  "kova browser close abcd1234",
  "kova browser screenshot",
  "kova browser screenshot --full-page",
  "kova browser screenshot --ref 12",
  "kova browser snapshot",
  "kova browser snapshot --format aria --limit 200",
  "kova browser snapshot --efficient",
  "kova browser snapshot --labels",
];

export const browserActionExamples = [
  "kova browser navigate https://example.com",
  "kova browser resize 1280 720",
  "kova browser click 12 --double",
  "kova browser click-coords 120 340",
  'kova browser type 23 "hello" --submit',
  "kova browser press Enter",
  "kova browser hover 44",
  "kova browser drag 10 11",
  "kova browser select 9 OptionA OptionB",
  "kova browser upload /tmp/kova/uploads/file.pdf",
  'kova browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "kova browser dialog --accept",
  'kova browser wait --text "Done"',
  "kova browser evaluate --fn '(el) => el.textContent' --ref 7",
  "kova browser console --level error",
  "kova browser pdf",
];
